### ISSUE TITLE
Scroll by Page

### ISSUE THREAD

**Issue by MentalGear** [voidcosmos/npkill#100]
**Is your feature request related to a problem? Please describe.**
It can take a long time scrolling the console list item by item when going over folders like /yarn, etc. Having shortcuts that would forward whole "pages" (e.g. one page of items visible on the console), would increase UX much.

**Describe the solution you'd like**
The H and L keys (next to j and k) could be used to scroll between pages.
Maybe also add these shortcuts to the intro text (in color).

PS: really helpful package, thx!

**Comment by richex-cn** [comment]
+1
Can also be support half page scroll using `Ctrl+D` and `Ctrl+U` like Vim or `d` `u`  like `less`.
