### ISSUE TITLE
Unknown error on delete (unlink) in windows

### ISSUE THREAD

**Issue by vazenfino** [voidcosmos/npkill#101]
**Describe the bug**
UNKNOWN: unknown error, lstat using npkill

**Screenshots**
![image](https://user-images.githubusercontent.com/51793206/116737917-6abfdc00-a9b7-11eb-9c15-cc505900b8d3.png)

 - OS: windows
 - Version [ npkill -v0.8.0 ]

**Comment by zaldih** [comment]
I have not been able to replicate the error.

With version 0.11.0 more details about the bug are shown so if it happens again in this version do not hesitate to reopen the issue.

Although it was probably related to other bugs that have already been fixed.
