### ISSUE TITLE
Allow full path in exclude

### ISSUE THREAD

**Issue by muescha** [voidcosmos/npkill#103]
**Is your feature request related to a problem? Please describe.**
i like to exclude some paths, but when i use a generic name like "Library" then it can also exclude it from unwanted leves

**Describe the solution you'd like**
allow a full path or an regex in the exclude `npx npkill --exclude "/Users/muescha/.pnp-store,/Users/muescha/Library"`

**Describe alternatives you've considered**
`npx npkill --exclude ".pnp-store,Library"` but then in lower directories this can exclude also a folder `Library`

**Additional context**

**Comment by zaldih** [comment]
Hey!
I have paid more attention to the `--exclude` command in the [latest version](https://github.com/voidcosmos/npkill/releases/tag/v0.11.1).

`--exclude` takes the parameters and compares them with the results (simple comparison without patterns/glob for now), so `npx npkill --exclude --exclude ".pnp-store/,Library/"` should work without problems in this case.

If you still have problems feel free to reopen the issue!
