### ISSUE TITLE
i like to exclude all "." directories

### ISSUE THREAD

**Issue by muescha** [voidcosmos/npkill#105]
**Is your feature request related to a problem? Please describe.**
i have a big list of node_modules in some "." directories (for example in `.pnpm-store`) 

**Describe the solution you'd like**
i like to have an option to exclude the dot folders like `--exclude-hidden-directories`

**Describe alternatives you've considered**

**Additional context**

**Comment by zaldih** [comment]
It is a very great idea!

I'm going to leave it pinned for a few days in case someone wants to work on it.

Currently all results have a property called 'isDangerous'. It is actually true if the particular result is located in some hidden directory.

The task would be to check if this flag is activated, skip showing it (or directly not add it to the results list)

**Comment by NeoLight1010** [comment]
Hello! I would like to work on this issue :D Please tell me if there are any special considerations for implementing this feature :smile:

**Comment by zaldih** [comment]
@NeoLight1010  Of course! All yours!

For now I can't think of any special considerations.
The easiest and best I think will be to directly filter these directories to ignore them and not add them to the list of results.
I suggest to implement the logic in the controller, in the main pipeline (about line 530).

If you have any doubt, do not hesitate to comment it

**Comment by zaldih** [comment]
What could be the short form of the flag?
For example for sort: `-s`, `--sort`
For `--exclude-hidden-directories` ?

cc @muescha @NeoLight1010

**Comment by muescha** [comment]
@Gulianrdgd found a good one: `-x`

**Comment by zaldih** [comment]
This change will be included in the upcoming 0.9.0 🎉 
Thanks for participating @muescha , @NeoLight1010 and @Gulianrdgd

**Comment by NeoLight1010** [comment]
No problem, and thank you for this amazing project! :D
