### ISSUE TITLE
Error on start 

### ISSUE THREAD

**Issue by FedericoMameliPrjs** [voidcosmos/npkill#11]
**Describe the bug**
when trying to execute the command npkill from any folder returns an error.
throw errnoException(err, 'spawn');

**Expected behavior**
Should allow me to select node_modules folders and delete

**Screenshots**
![image](https://user-images.githubusercontent.com/37149443/63059813-b2a38480-bef0-11e9-845b-63cfaee82c9a.png)

 - OS: Windows 7
 - Version 0.3.0

**Comment by NyaGarcia** [comment]
Oh no! Will look in to it and provide a solution as soon as possible. Sorry for the inconvenience :(

**Comment by NyaGarcia** [comment]
I executed the basic npkill command without any parameters from my user on Windows 7 (64-Bit). To try out a different scenario, I also executed the command with parameters (npkill -f -c magenta). Here are both results:

![npkill](https://user-images.githubusercontent.com/37065748/63064020-880cf800-beff-11e9-9853-dbf190aa2242.gif)

As you can see, npkill was executed without any errors on both occasions. Perhaps you have an outdated Node.js version? I am using version 10.16.2, as you can see in the following capture:

![image](https://user-images.githubusercontent.com/37065748/63063831-94448580-befe-11e9-9d63-46120dcbd8ac.png)

If after updating Node.js the problem persists, I will once again look into and try to solve it.

**Comment by FedericoMameliPrjs** [comment]
I download the latest version, I think.I'll try to reinstall node and see if it solves.Thanks!

Inviato da Yahoo Mail su Android 
 
  Il gio, 15 ago, 2019 alle 1:58, Nya<notifications@github.com> ha scritto:   
I executed the basic npkill command without any parameters from my user on Windows 7 (64-Bit). To try out a different scenario, I also executed the command with parameters (npkill -f -c magenta). Here are both results:



As you can see, npkill was executed without any errors on both occasions. Perhaps you have an outdated Node.js version? I am using version 10.16.2, as you can see in the following capture:



If after updating Node.js the problem persists, I will once again look into and try to solve it.

**Comment by NyaGarcia** [comment]
Hi :) Did you manage to solve the problem?

**Comment by FedericoMameliPrjs** [comment]
Hi, I've checked the node version and it is the 10.2 ...
I've tried to run after restarting windows and it still give me the same error...    Il domenica 18 agosto 2019, 12:04:37 CEST, Nya <notifications@github.com> ha scritto:  
 
 
Hi :) Did you manage to solve the problem?

**Comment by zaldih** [comment]
I have a hypothesis of what is happening at this point.

Npkill uses an executable binary (exe) to perform searches much faster. I think that your antivirus could have given a false positive during installation and that it would have been deleted.

This could be confirmed as follows:
Go to %appdata%\roaming\ npm\node_modules\npkill\lib/bin
- **Can you see one in that path, a file called _windows-find.exe_?**

If so, HURRA! localized problem
In this case, the possible solutions could be:
- a. Add the file to the white list of your antivirus and reinstall npkill.
- b. Download the source, build the package yourself and install it


If that is not the problem or you have any other questions, do not hesitate to write to us If that is not the problem or you have any other questions, do not hesitate to write to us :smile:

**Comment by FedericoMameliPrjs** [comment]
HI, Ok, maybe the problem is the antivirus, I'll try and I'll give you a feedback. I have another "problem", with Windows 10 this time. It works but when finishes deleting throws an error and exit,so I have to restart the script. 
C:\Users\Scuola\AppData\Roaming\npm\node_modules\npkill\lib\services\windows-files.service.js:18                    throw err;                    ^
Error: ENOENT: no such file or directory, lstat 'C:\Users\Scuola\Desktop\Smart contact\libs\exit-popup\node_modules\.bin'
What can be?
Thanks for the availability!
    Il lunedì 19 agosto 2019, 02:48:11 CEST, Juan Torres <notifications@github.com> ha scritto:  
 
 
I have a hypothesis of what is happening at this point.

Npkill uses an executable binary (exe) to perform searches much faster. I think that your antivirus could have given a false positive during installation and that it would have been deleted.

This could be confirmed as follows:
Go to %appdata%\roaming\ npm\node_modules\npkill\lib/bin
   
   - Can you see one in that path, a file called windows-find.exe?

If so, HURRA! localized problem
In this case, the possible solutions could be:
   
   - a. Add the file to the white list of your antivirus and reinstall npkill.
   - b. Download the source, build the package yourself and install it

If that is not the problem or you have any other questions, do not hesitate to write to us If that is not the problem or you have any other questions, do not hesitate to write to us 😄

**Comment by zaldih** [comment]
We are aware of that bug. It usually happens when a directory is deleted and its size has not yet been calculated (shown -- in its size).
Thank!

**Comment by zaldih** [comment]
I will close the issue.
If you have any news, do not hesitate to comment!

a greeting
