### ISSUE TITLE
 Cannot read properties of undefined (reading 'path')

### ISSUE THREAD

**Issue by tomatobybike** [voidcosmos/npkill#116]
**Describe the bug**

**To Reproduce**
1. Go to react project dir
2. Command 'npkill'
3. type space
3. See error

**Expected behavior**

**Screenshots**

 - OS: [MacbookPro]
 - Version [v0.8.2 ]
 - NodeJs Version v16.13.0
 - 
**Additional context**

**Comment by zaldih** [comment]
This issue should be resolved. As of version `v0.11.0` it is possible to see the details of the errors that occur.
