### ISSUE TITLE
node_modulesdules (existing text isn't cleared in the console when writing to a line again)

### ISSUE THREAD

**Issue by xMGZx** [voidcosmos/npkill#118]
**Describe the bug**
"node_modulesdules" as caused by overwriting existing text without clearing the line fully.

**To Reproduce**
1. Eat a banana
2. Run npx npkill on a specific machine
3. Delete a folder

**Expected behavior**
"node_modules" not "node_modulesdules"

**Screenshots**
![image](https://user-images.githubusercontent.com/40220050/148484811-9ed04f1a-aec7-4f03-b410-147c80c9d7a3.png)

 - OS: Windows 10
 - npkill v0.8.2

**Comment by zaldih** [comment]
Fixed on `v0.11.1` 🎉
