### ISSUE TITLE
ţ̯̬͙͙̹̙͎͛͐͂̀̅̀͠͡e̸ͫͦ̾̍ͥ̈ͨͮ̀̒̍̋͗̑̓͂̈ͦ ҉̖͕̙̳͍͔̫͓̮͕̙̻͙̗̻͠͠͞s͕͖͈͔̤̬̎̈͐̉ͫ̐ͦ̐ͧ͘͜͟͡t͛ͦͬͮͬ͑̉ͨ̉̀͛̽͗͐ͣ̆ͭ̃͐i̸̶͖͚͖̍̑ͬͤ̓̀̎̑͛̾̍ͩͨ͠ń̹̠̣͈̥͐͗ͫ̑̆ͥͤ̃ͨ́͜͡ͅg̵̲̀̒̋͐ͤ̅̀ͪ̒ͥ̓̃̉̃̀́̚ ̷̛͙̞͚̓ͥͦ̏̇ͫ̂ͭͤ̒ͩ̈̕͠tͨ̊̓͐̐͌͛ͤͭͭͪ̈̓̏̾ ҉̨͙̺̪̙̦̤̣͖́͞͠e͗̈̓̇̽̉̓̾ͨ͌͋̏ͦ̐ͫͨͩ̍̀s̶̷͓̼̥͕͍̫̙ͥ̉̾̋̓͗͆͜͟͠t̵̛͍ͪͬ̊ͩ̒̑ͫ̅̔ͫ͗̑ͦ̽̎͐i̷̼̭̰̙̫͍̗̅͗ͣ̋͋̉ͦ̓͋̚͞n̸̢̮̫̼̟̮͚̗̺̺̜ͧͮ̀͑̌͗͛g̢̛͚̟̜̞ͥ̓ͤ͑̓̉̊͊̓̊́̀͞  when running on macos

### ISSUE THREAD

**Issue by DumbGameMaker** [voidcosmos/npkill#119]
**Describe the bug**
When I run npx npkill, it outputs the word testing, but filled with zalgo like 

ţ̯̬͙͙̹̙͎͛͐͂̀̅̀͠͡e̸ͫͦ̾̍ͥ̈ͨͮ̀̒̍̋͗̑̓͂̈ͦ ҉̖͕̙̳͍͔̫͓̮͕̙̻͙̗̻͠͠͞s͕͖͈͔̤̬̎̈͐̉ͫ̐ͦ̐ͧ͘͜͟͡t͛ͦͬͮͬ͑̉ͨ̉̀͛̽͗͐ͣ̆ͭ̃͐i̸̶͖͚͖̍̑ͬͤ̓̀̎̑͛̾̍ͩͨ͠ń̹̠̣͈̥͐͗ͫ̑̆ͥͤ̃ͨ́͜͡ͅg̵̲̀̒̋͐ͤ̅̀ͪ̒ͥ̓̃̉̃̀́̚ ̷̛͙̞͚̓ͥͦ̏̇ͫ̂ͭͤ̒ͩ̈̕͠tͨ̊̓͐̐͌͛ͤͭͭͪ̈̓̏̾ ҉̨͙̺̪̙̦̤̣͖́͞͠e͗̈̓̇̽̉̓̾ͨ͌͋̏ͦ̐ͫͨͩ̍̀s̶̷͓̼̥͕͍̫̙ͥ̉̾̋̓͗͆͜͟͠t̵̛͍ͪͬ̊ͩ̒̑ͫ̅̔ͫ͗̑ͦ̽̎͐i̷̼̭̰̙̫͍̗̅͗ͣ̋͋̉ͦ̓͋̚͞n̸̢̮̫̼̟̮͚̗̺̺̜ͧͮ̀͑̌͗͛g̢̛͚̟̜̞ͥ̓ͤ͑̓̉̊͊̓̊́̀͞

**To Reproduce**
1. macos 11.5.1 on m1 with macports
2. Command npx npkill
3. See error

**Expected behavior**
The npkill UI

**Screenshots**
If applicable, 
![Screen Shot 2022-01-08 at 5 16 48 PM](https://user-images.githubusercontent.com/61807031/148665432-627389fc-6068-4262-ad9c-99f03dd9843a.png)
add screenshots to help explain your problem.

 - OS: [e.g. Window] macos 
 - Version [ npkill -v ] legit no idea this command won't show me because ţ̯̬͙͙̹̙͎͛͐͂̀̅̀͠͡e̸ͫͦ̾̍ͥ̈ͨͮ̀̒̍̋͗̑̓͂̈ͦ ҉̖͕̙̳͍͔̫͓̮͕̙̻͙̗̻͠͠͞s͕͖͈͔̤̬̎̈͐̉ͫ̐ͦ̐ͧ͘͜͟͡t͛ͦͬͮͬ͑̉ͨ̉̀͛̽͗͐ͣ̆ͭ̃͐i̸̶͖͚͖̍̑ͬͤ̓̀̎̑͛̾̍ͩͨ͠ń̹̠̣͈̥͐͗ͫ̑̆ͥͤ̃ͨ́͜͡ͅg̵̲̀̒̋͐ͤ̅̀ͪ̒ͥ̓̃̉̃̀́̚ ̷̛͙̞͚̓ͥͦ̏̇ͫ̂ͭͤ̒ͩ̈̕͠tͨ̊̓͐̐͌͛ͤͭͭͪ̈̓̏̾ ҉̨͙̺̪̙̦̤̣͖́͞͠e͗̈̓̇̽̉̓̾ͨ͌͋̏ͦ̐ͫͨͩ̍̀s̶̷͓̼̥͕͍̫̙ͥ̉̾̋̓͗͆͜͟͠t̵̛͍ͪͬ̊ͩ̒̑ͫ̅̔ͫ͗̑ͦ̽̎͐i̷̼̭̰̙̫͍̗̅͗ͣ̋͋̉ͦ̓͋̚͞n̸̢̮̫̼̟̮͚̗̺̺̜ͧͮ̀͑̌͗͛g̢̛͚̟̜̞ͥ̓ͤ͑̓̉̊͊̓̊́̀͞

**Additional context**

**Comment by DumbGameMaker** [comment]
for some reason when i try using grep to exclude all the testing stuff I get this
![Screen Shot 2022-01-08 at 5 24 31 PM](https://user-images.githubusercontent.com/61807031/148665612-3dca14e3-8bbf-47c6-850f-2afa7cd90dc8.png)
is this like an easter egg or something? am I getting MITM'd?

**Comment by DumbGameMaker** [comment]
I'm literally digging through all the npkill code on my machine and nothing has anything related to this issue

**Comment by DumbGameMaker** [comment]
seems like the problem is somewhere in lib/controller.js

**Comment by DumbGameMaker** [comment]
found it. looks like the colors module does this as an artifact of debug.
![Screen Shot 2022-01-08 at 5 56 09 PM](https://user-images.githubusercontent.com/61807031/148666207-f7ffe844-e50d-42a0-9a09-571fe6a4a273.png)

**Comment by DumbGameMaker** [comment]
https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6#diff-92bbac9a308cd5fcf9db165841f2d90ce981baddcb2b1e26cfff170929af3bd1R18

**Comment by DumbGameMaker** [comment]
it's because marak isn't getting paid so he vandalized his very popular package. fix by changing colors dependency from latest to 1.4.0

**Comment by zaldih** [comment]
Thank you very much for pointing out this issue and for your research.
We have launched a new version fixing the problem.
