### ISSUE TITLE
`--sort=size` doesn't work

### ISSUE THREAD

**Issue by ljharb** [voidcosmos/npkill#120]
Double-dashed/long options should *always* use `=`, altho it's fine if they don't require it. It seems like npkill only works without an `=` on long options. Can this either be fixed so it works with this standard usage, or, error eagerly so i don't have to wait for all the results before finding out it's not sorted?

**Comment by zaldih** [comment]
Thanks for opening the issue!

You are right. It should be an option to define the parameters with = although this is not mandatory according to e.g. https://nullprogram.com/blog/2020/08/01/ .

So in the next version it will be possible to use both the classic way and the new one with `=`  😃

**Comment by ljharb** [comment]
I agree it's not mandatory, but it's a pretty overwhelming convention to include the = :-)

**Comment by ljharb** [comment]
Thanks!
