### ISSUE TITLE
.gitignore equivalent for ignored directories

### ISSUE THREAD

**Issue by bennetfabian** [voidcosmos/npkill#123]
**Is your feature request related to a problem? Please describe.**
Not necessarily related to a problem.

**Describe the solution you'd like**
I think there should be the equivalent of .gitignore file in Git but for npkill.
There you should be able to specify directories that should never be scanned for node_modules folders.

**Describe alternatives you've considered**

**Additional context**
What this could be useful for?
For example to exclude Atom & Visual Studio Code code editor extensions which are typically written in JavaScript/TypeScript.

**Comment by zaldih** [comment]
Thank you for the suggestion and sorry for not replying sooner.

I thought about the idea but I think it's adding too much complexity to something that could be achieved with an alias in the shell (something like `alias npkill=npx npkill --exclude "dir1,dir2,..."`).

However, in the future I have thought of adding a global configuration file that takes into account the idea of this "ignored directories" issue.
