### ISSUE TITLE
Highlight entire row including the size

### ISSUE THREAD

**Issue by goldbuick** [voidcosmos/npkill#14]
Can the entire row be highlighted so it is easier to read how much space that particular row takes up.

**Comment by zaldih** [comment]
Good idea! It could be a very interesting option especially for users who run the program with a wide terminal.

### Public survey.
 **Which mode can be more comfortable and enjoyable? A or B?** _(It's not yet developed, it's just a recreation)_

![row highlight modes](https://user-images.githubusercontent.com/16844185/63113534-05357d00-bf93-11e9-8269-cd122e6e3dcb.png)

**Comment by Caballerog** [comment]
Option A

**Comment by zaldih** [comment]
Working at #20 
In the next update this feature will be included

**Comment by NyaGarcia** [comment]
Just published a release that includes this feature :)
