### ISSUE TITLE
Getting SyntaxError: Unexpected token '.' during npkill launch

### ISSUE THREAD

**Issue by sourabhbagrecha** [voidcosmos/npkill#141]
**Describe the bug**
Just did a fresh install for the first time on my MacOS, and the installation went fine. But once I launch the process, it fails with the following error
```
node_modules/npkill/lib/services/files.service.js:37
        return sorted[0]?.modificationTime || null;

SyntaxError: Unexpected token '.'
```

Even `npkill -v` is causing the same issue.

**To Reproduce**
1. Install npkill using `npm i -g npkill`
2. Execute: `npkill`

Or just `npx npkill` is also returning the same issue.

**Expected behavior**
I was expecting it to start listing down all the `node_modules` folders with their size.

**Screenshots**
<img width="800" alt="image" src="https://user-images.githubusercontent.com/27056663/215254329-68d83a23-aca3-40e7-bbfd-81be4a973dca.png">

 - OS: MacOS Monterey v12.5 M1 Pro
 - Version 0.10.0

**Comment by zaldih** [comment]
Hey!  Thank you very much for opening this issue. 

Could you confirm which version of node you have? 

If your node version is <14 then npkill will not work and you can use launch a old version with npkill@0.8.3. 

Otherwise it will indeed be a bug.

**Comment by sourabhbagrecha** [comment]
Hey @zaldih, I switched to v14 and it worked! Thank you. 
Can we add a warning in place when users try to execute it from a lower than supported version? 
It will save a lot of time. Thanks.

**Comment by zaldih** [comment]
It would be a good idea but, how could we do it?

The error appears as soon as the import(main) function appears in main.js and before main is imported no code execution can be done.

One way I have thought of is to run an intermediate script that does the check and then executes the program but it is an additional complexity that I would not like to add.

So I think it's best to leave it like this. There are already formal warnings in both the readme and the package.json (engines section).

If you have another idea in mind I would like to hear it!
