### ISSUE TITLE
Freezes calculating stats

### ISSUE THREAD

**Issue by hd321kbps** [voidcosmos/npkill#149]
If you do not wait for the scan and size calculation.
Delete the folder whose size has not yet been calculated.
The calculation of statistics freezes, the size of folders is no longer calculated. Well, the stats are wrong.)
Errors: ENOENT: no such file or directory

**Comment by zaldih** [comment]
Thank you for opening the issue.
Could you tell me on which OS it happens and which version of npkill?

**Comment by hd321kbps** [comment]
Windows 11, npkill 0.11.0

**Comment by zaldih** [comment]
Thank you very much. I will look into it :)

**Comment by FrankCheungCN** [comment]
I have encountered the same problem. I just use `-gb` to show folders in Gigabytes instead of Megabytes then i works.

**Comment by marckraw** [comment]
yup, same for me, by default the app freezes, but when passed `-gb` option, it works fine :)

**Comment by zaldih** [comment]
Thank you for providing the reports.
Although I have not been able to replicate the error yet I suspect the problem has to be [here](https://github.com/voidcosmos/npkill/blob/b7b32504f2913fd60470cafd08e67178afd0f2b1/src/ui/components/results.ui.ts#L166).
As soon as I have some time I will dig further.

In npkill@0.11.0 this problem should not occur.

**Comment by supoved** [comment]
can confirm same bug in version `v0.11.1` and same workaround with `-gb` flag working
Apple M1, MacOS 13.0.1

**Comment by glyder** [comment]
who is looking at this, can you simply just remove the scanning of "calculating stats", "size". On HDD this is painfully slow. I simply want to delete my node_modules.

**Comment by zaldih** [comment]
I have just launched version 0.11.2 . Could you please check that this problem has been solved?
**npx npkill@latest**

**Comment by zaldih** [comment]
@glyder I like your idea. I encourage you to open a new specific issue to discuss what would be the best option for managing that :)

**Comment by marckraw** [comment]
seems to be working now for me :)

**Comment by hd321kbps** [comment]
0.11.2 this issue is relevant
