### ISSUE TITLE
Moving back to an item that has started deleting, or is deleted, disables the arrow key and produces error

### ISSUE THREAD

**Issue by espenja** [voidcosmos/npkill#156]
**Describe the bug**
When deleting a folder and using the arrow keys to move up and down the list, if you go back to an item you have started to delete, the arrow keys will stop working and npkill will show errors

**To Reproduce**
1. Go to a package or workspace root
2. Run command `npkill`
3. Move down to a random item in the list
4. Press space to start deleting
5. Move down
6. Move up again to the item that has started deleting, or is deleted
7. Error occurs and the arrow key in the direction you moved to produce the error is seemingly disabled
8. Press e to view error (attached in screenshot section)

**Expected behavior**
Arrow keys should continue moving up and down the list, regardless of having started deleted an item, or the item having been deleted or not

**Screenshots**
![image](https://user-images.githubusercontent.com/1131968/230083747-dd15e2d9-94eb-4a82-9611-824d95e4e3fc.png)

- OS: Version: OS Name	Microsoft Windows 11 Enterprise 10.0.22621 Build 22621
- npkill version: v0.11.1
- Other:
  - Node v16.19.1
  - volta 1.1.1 (nvm alternative)

**Additional context**
- I am using `volta` to manage node versions.
- I am in a pnpm monorepo with multiple packages

**Comment by zaldih** [comment]
Hi!
Thank you very much for opening the issue with so many details. I will investigate the problem in these days.

**Comment by espenja** [comment]
I have tested with version 0.11.2, and it seems like that does the trick :) I'm no longer getting a locked arrow experience after deleting directories. Thank you for the quick fix, great work ⭐
