### ISSUE TITLE
Invalid count value

### ISSUE THREAD

**Issue by andromidasj** [voidcosmos/npkill#157]
**Describe the bug**
Whenever running npx npkill, with or without option flags, I get an `Invalid count value` error. Using the arrow keys to select 'up' or 'down', the error count increments, and upon inspecting the errors by hitting `e`, they are all the same error: `RangeError: Invalid count value` on the 0th index, and `Invalid count value` on the rest. (See screenshot below.)

At this point, everything is broken and unresponsive, and needs to be cancelled with `CTRL+C`. This is reproducible for me on three different terminals: macOS Terminal, Tabby, and Warp.

**To Reproduce**

1. Running `npx npkill`
2. Wait for scanning, and when the progress bar is about 2/3 the way through, it'll show a message at the top `1 error. 'e' to see`

**Expected behavior**
I expect the utility to run without errors.

**Screenshots**
<img width="947" alt="image" src="https://user-images.githubusercontent.com/66661368/230963686-2c174e5a-f105-41c3-a438-4e63658f6e0f.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/66661368/230964415-74418c04-8d20-4d0a-8018-56d570e0d6f0.png">

- OS: `macOS 13.3.1 (22E261)`
- Version [ npkill -v ]: `v0.11.1%`

**Additional context**
This happens with or without flags (-x, -s size, etc). While troubleshooting, and on my first try with the built-in macOS terminal, it actually performed a successful run-through. I then decided to add the flags above, and then got the same error. When trying again without any flags, I could not reproduce a successful run-through again, and it would fail every time.

**Comment by andromidasj** [comment]
Update: My first run-through of `npx npkill` (with no flags) on iTerm worked without a problem. I deleted a couple of folders presumably successfully, but then when I resized the screen all the options disappeared (guess that's on me?), but then I'd get the same errors as the original post.

I hit `CTRL+C`, ran `npx npkill` one more time, and now it fails just like the other ones.

**Comment by andromidasj** [comment]
One more troubleshooting update: looks like a single repository was causing npkill to crash. When I excluded a specific repo using the `-E` flag, it reliably works now! The repo in question was a cloned repo from https://github.com/sct/overseerr. Not sure why it broke npkill though.

**Comment by zaldih** [comment]
Thank you very much for opening the issue with all the details!

It seems that the same problem is described the issue #149 .
I just released version 0.11.3 which should fix the problem, could you check it?

**Comment by zaldih** [comment]
Closing as resolved. If the problem persists feel free to reopen it.

**Comment by mortalYoung** [comment]
I got this problem in v0.11.3. I have no idea about what happened.
<img width="1430" alt="image" src="https://github.com/voidcosmos/npkill/assets/18719701/c5543788-9ef9-4d54-a979-d0243e7a9b5e">

**Comment by mortalYoung** [comment]
I found once I removed the `node_modules` under `./apps/myProject/`（my project is based on turbo）, It would work again! 
Would you mind tell me the reason so I could prevent it happened again?
