### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'message')

### ISSUE THREAD

**Issue by milindgoel15** [voidcosmos/npkill#159]
**Describe the bug**
Gives a typeerror TypeError: Cannot read properties of undefined (reading 'message')
Not sure how to fix it myself

**To Reproduce**

1. Open terminal
2. Run `npx npkill`
3. Error occurs

**Expected behavior**
No error

**Screenshots**
![image](https://user-images.githubusercontent.com/45682747/232399505-67c5334f-dda9-4333-800f-7797a28ff78b.png)

- OS: Windows 11 22h2
- Version [ npkill -v ]: 0.11.2

**Additional context**
na

**Comment by zaldih** [comment]
Thank you for reporting the bug!
I seem to have missed something when checking for Uncaught errors during a recent code refactor.

I will release a patch in the next few days fixing this.
