### ISSUE TITLE
Sort results by size

### ISSUE THREAD

**Issue by trueter** [voidcosmos/npkill#16]
**Is your feature request related to a problem? Please describe.**
I ran npkill on `/`. The result was a terribly long list. I couldn't reach the bottom in reasonable time.

**Describe the solution you'd like**
Either automatically sort results by folder size or offer hotkey to do so

**Describe alternatives you've considered**
%

Very useful tool so far. Cleared 2gb in the first round, but couldn‘t get to the "bottom of it" for the above reason.

**Comment by NyaGarcia** [comment]
Great suggestion. We will add a new option to sort by size. Thank you for opening an issue :D
