### ISSUE TITLE
Help command does not print all the result in the large-size window

### ISSUE THREAD

**Issue by fyfirman** [voidcosmos/npkill#160]
**Describe the bug**
At some point, whenever you enlarge the terminal window and run the help command it does not print all the commands. However, it can be solved by making the terminal smaller.

**To Reproduce**

1. Enlarge the terminal
2. Run `npx npkill --help`
3. See the result

**Expected behavior**
All the command result is printed

**Screenshots**
![image](https://user-images.githubusercontent.com/37064641/232621927-1f06c58a-4fc0-469e-a472-56530333ab9b.png)
The list of commands is missing. 

- OS: MacOS
- Version v0.11.2

**Comment by zaldih** [comment]
Fixed in #161 . Thank!
