### ISSUE TITLE
0.12.0 Cannot read `windowsStrategyManager` of undefined

### ISSUE THREAD

**Issue by aphex** [voidcosmos/npkill#177]
**Describe the bug**
When running `pnpm dlx npkill` and pressing space on a folder I get the error 
"Cannot read properties of undefined (reading 'windowsStrategyManager')" 

This one seems to happen on version 0.12.0. running `pnpm dlx npkill@0.11.3` works fine.

**To Reproduce**
`pnpm dlx npkill` 
Attempt to delete a folder

**Expected behavior**
Should delete `node_module`

**Screenshots**
![image](https://github.com/voidcosmos/npkill/assets/152484/cf47a298-a27f-4e38-967c-7ef5d0f10f70)

- OS: Windows 11
- Version 0.12.0

**Comment by TheMikeyRoss** [comment]
Same here 

![image](https://github.com/voidcosmos/npkill/assets/97709651/5bfd16e8-ff5d-4483-af71-0a0a30d0bd98)


Everything was working fine before the update `npx npkill` worked like a charm. Now

1- Takes too long to load
2- nothing shows up in the terminal until I move the cursor up or down
3- the error in the screenshot above not letting us actually delete the `node_modules`

**Comment by zaaakher** [comment]
A temporary workaround while this issue is waiting a fix is running `npx npkill@0.11.3` to use the previous release to delete your node_modules without issues.

**Comment by zaldih** [comment]
Thank you very much for reporting the problem. I will look into it.

**Comment by zaldih** [comment]
It should be fixed now in 0.12.1. 
If you have any other problems, don't hesitate to open issue! (if this one hasn't been solved, please let me know).
