### ISSUE TITLE
Nothing shows up in the terminal until I press any key

### ISSUE THREAD

**Issue by TheMikeyRoss** [voidcosmos/npkill#178]
**Describe the bug**
When I run `npx npkill` it shows "calculating stats" loading for a very very long time with no actual node_module paths in the list. I waited for 10 minutes and still nothing showed up.

Once I pressed the down arrow, all the paths showed up (but without size or last_mod)

**To Reproduce**

1. Be in windows 10
2. Run `npx npkill`
3. Stare at the terminal and wait indefinitely and you won't see any of the paths of the node_modules
4. Once you press any key in your keyboard then you'll see all the paths

**Expected behavior**
It should show me the list of paths similar to the gif in the README.md

**Screenshots**
I've been staring at this screen 👇 for a very long time
![image](https://github.com/voidcosmos/npkill/assets/97709651/8aed891f-2434-4060-97d3-fe71feef4ba5)

- OS: Windows
- Version v0.12.1

**Comment by zaldih** [comment]
Thanks for reporting these problems with v0.12.x .
I seem to have broken quite a few things in windows 😅

**Comment by zaldih** [comment]
Fixed in [v0.12.2](https://github.com/voidcosmos/npkill/releases/tag/v0.12.2).
