### ISSUE TITLE
Size and last_mod are missing in v0.12.1

### ISSUE THREAD

**Issue by TheMikeyRoss** [voidcosmos/npkill#179]
**Describe the bug**
When I run `npx npkill` I face this issue https://github.com/voidcosmos/npkill/issues/178 and then when I press any key I see the paths but the last_mod and size are missing (see screenshots below)

**To Reproduce**

1- Be in windows 10
2- Run npx npkill
3- Press any key to make the paths show up (from the issue https://github.com/voidcosmos/npkill/issues/178)
4- No matter how long you wait, you won't be able to see the size or last_mod

**Expected behavior**
It should show the size and last_mod (or at least just the size) similar to the gif in the readme.md

**Screenshots**

The screenshot below is after 10+ minutes wait

![image](https://github.com/voidcosmos/npkill/assets/97709651/8925c635-45c9-4f41-a12c-160ef1a55fe2)

- OS: Windows
- Version v0.12.1

**Comment by zaldih** [comment]
Fixed in [v0.12.2](https://github.com/voidcosmos/npkill/releases/tag/v0.12.2).
