### ISSUE TITLE
Releasable space & space saved are stuck in zero

### ISSUE THREAD

**Issue by TheMikeyRoss** [voidcosmos/npkill#180]
**Describe the bug**
After I delete some node_modules, the releasable space and "space saved" don't change and they're always stuck at zero. (this could be related to #179 

**To Reproduce**

1. Be in Windows 10
2. Run `npx npkill`
3. Press any key to make the node_modules show up (#178)
4. Press space to actually delete a node modules 
5. Notice that the "space saved" and "releasble space" don't change and are always stuck at zero

**Expected behavior**
It should actually reflect the true sizes of "releasble space" and "space saved"

**Screenshots**
![image](https://github.com/voidcosmos/npkill/assets/97709651/3f838597-97f9-4521-ab95-322a6514ee72)

- OS: Windows 10
- Version v0.12.1

**Comment by zaldih** [comment]
Fixed in [v0.12.2](https://github.com/voidcosmos/npkill/releases/tag/v0.12.2).
