### ISSUE TITLE
"Calculating stats" is stuck loading forever

### ISSUE THREAD

**Issue by TheMikeyRoss** [voidcosmos/npkill#181]
**Describe the bug**
After running `npx npkill` and actually deleting all the node_modules . The "calculating stats" in the top right corners is just loading infinitely 

**To Reproduce**

1. Be in Windows 10
2. Run `npx npkill`
3. Delete all the node_modules you see
4. Notice the "calculating stats" loading infinitely 

**Expected behavior**
It should reflect actual stats calculation where the loading will show up during calculation and then stops when the calculations are done.

**Screenshots**
I could've included a gif showing the actual loading (and the asci animation) but I can't record a gif atm. 
The "calculating stats" you see in the screenshot below is just loading infinitely 

![image](https://github.com/voidcosmos/npkill/assets/97709651/99c50088-c03b-4412-887b-3d8222200dfb)

- OS: Windows 10
- Version v0.12.1

**Comment by zaldih** [comment]
Fixed in [v0.12.2](https://github.com/voidcosmos/npkill/releases/tag/v0.12.2).
