### ISSUE TITLE
Calculating stats is  loading infinity, don't show the size 

### ISSUE THREAD

**Issue by mehedi-imun** [voidcosmos/npkill#182]
![image](https://github.com/voidcosmos/npkill/assets/92694753/78ad519b-4b10-4482-b767-97d61b75841f)

**Comment by zaaakher** [comment]
Duplicate of #181 

In the meantime, you can use `npx npkill@0.11.3`

**Comment by zaldih** [comment]
Thank you for opening this issue.
As the colleague says, this problem is related to the other issue. Let's follow this there.

**Comment by mehedi-imun** [comment]
Thank you
