### ISSUE TITLE
[Feature request] Exclude directory option

### ISSUE THREAD

**Issue by GaurangTandon** [voidcosmos/npkill#19]
**Is your feature request related to a problem? Please describe.**

I wish to search through all directories in `~` except a few directories. Those few directories have active projects that I know I am working on and I do not want to run npkill on them.

**Describe the solution you'd like**

Pass a list of exclude directories, something like `npkill --exclude-dir ~/my-projects/*` which should make sure that `npkill` doesn't try to search inside the directory `~/my-projects`.

**Describe alternatives you've considered**

I haven't.

**Additional context**

Not necessary.

**Comment by NyaGarcia** [comment]
Great request :) It is actually one of the features in our TODO list, and will be available shortly. Thanks anyway for your suggestion!

**Comment by NyaGarcia** [comment]
This feature is now available in the newly released :fireworks: 0.6.0 version :fireworks:
You can exclude directories by using -E or --exclude options.

**Comment by pawel2105** [comment]
This feature is not working. I'm on v0.6.0 and each of the following 4 command variants:

```
npkill --exclude "/Users/pawel/Library/Caches/Yarn/*,"
npkill --exclude "/Users/pawel/Library/Caches/Yarn/*"
npkill --exclude "/Users/pawel/Library/Caches/Yarn"
npkill --exclude "/Users/pawel/Library/Caches/Yarn,"
```

Will still list directories like below:

```
/Users/pawel/Library/Caches/Yarn/v1/npm-fsevents-1.1.3-11f82318f5fe7bb2cd22965a108e9306208216d8/node_modules
/Users/pawel/Library/Caches/Yarn/v1/npm-fsevents-1.2.3-08292982e7059f6674c93d8b829c1e8604979ac0/node_modules
```

**Comment by muescha** [comment]
@pawel2105 you can only use a folder name, in your case the `"Yarn"`
