### ISSUE TITLE
I released the same idea few days ago

### ISSUE THREAD

**Issue by run1t** [voidcosmos/npkill#24]
Few days ago, I released [nmc](https://github.com/run1t/nmc) on github. It's a go project that aim to provide a simple command line to list all of the `node_modules` in a folder and delete all of them.

Basically it's the same idea that `npkill` with a lot less features 😅 

This morning when I saw your project in trending I find it very cool to see exactly what I wanted to do, already done 👍 
Good job !
Tell me how I can help 😃  
I will archive my project and will put some efforts in yours instead 😃

**Comment by NyaGarcia** [comment]
First of all, nice job with nmc! :smile: 
We'd love to have you collaborating with us, it'd be awesome. We're working on putting together a contributing.md to make collaborating easier, will let you know as soon as its done (hopefully today :yum:) Thank you
