### ISSUE TITLE
The unit confusion

### ISSUE THREAD

**Issue by zhylmzr** [voidcosmos/npkill#26]
The display units for this tool are `mb` and `gb`. Usually I think `8mb = 1MB`, `gb` is the same, but I found the `convertBToKb` method in the code, the parameter name is `bytes`, then `b` is `bit` or `byte`?

**Comment by zhylmzr** [comment]
Because I found that when I searched, the tool showed more than `300gb` of releasable space, but my hard drive only had more than `200GB`. If the displayed unit is `bit`, everything looks fine. But when I try The size of the conversion display compares it to the actual size and finds that the sizes of the two are inconsistent.

![Snipaste_2019-08-21_10-10-11](https://user-images.githubusercontent.com/15730824/63398567-9b88f900-c400-11e9-9534-bc923fa73f57.png)

![Snipaste_2019-08-21_10-15-19](https://user-images.githubusercontent.com/15730824/63398580-a3e13400-c400-11e9-8b9e-b43f87ef35e3.png)

![Snipaste_2019-08-21_10-42-47](https://user-images.githubusercontent.com/15730824/63398611-ba878b00-c400-11e9-8525-aecfb0879146.png)

![Snipaste_2019-08-21_10-43-51](https://user-images.githubusercontent.com/15730824/63398622-c2472f80-c400-11e9-83f2-0e02a10f0ec8.png)

**Comment by zaldih** [comment]
Hi!  Thank for opening the issue.

Indeed, convertBToKb should be convertBytesToKb.

I will review all conversions right now.
It seems that this problem is similar to what was in this issue #13 .
Can you tell me the version with `npkill -v`?

**Comment by zhylmzr** [comment]
@zaldih  The version is `v0.4.2`.

**Comment by zaldih** [comment]
Thank you.
A problem similar to what happened in # 28 and I missed it a lot.
I will investigate the origin of the problem, although I cannot easily replicate it.
Feel free to open PR if you want to change the name of the method oand if you discover a solution.

**Comment by zaldih** [comment]
As this issue seems to be resolved, I will close it.
