### ISSUE TITLE
Releasable space is much more than my SSD size

### ISSUE THREAD

**Issue by kvolkovich-sc** [voidcosmos/npkill#28]
Hi. 

I run `sudo npkill`.

`releasable space` is `471.05 gb`, but I have only 250 gb on my Mac Mini's SSD drive.

**Comment by zaldih** [comment]
Hi!
There seems to be an error in unit conversions that we thought was fixed.
Could you verify that you have version 0.4.x? `npkill -v`
And could you tell me if a large number of node_modules results appear?

**Comment by kvolkovich-sc** [comment]
`npkill -v` => `v0.4.2`

**Comment by kvolkovich-sc** [comment]
Hm. It's strange. But on the second run it shows `37 gb`.

**Comment by kvolkovich-sc** [comment]
I also noticed that sometimes units are displayed as `xx gbb` instead of `xx gb`. 

Maybe it was an issue with terminal content refreshing and not related to the wrong size calculating.

I use iTerm 2.

**Comment by zaldih** [comment]
Dafuq.
That is very rare. I imagine that you have executed the command again under the same conditions (?)

**Comment by kvolkovich-sc** [comment]
Same terminal session.

**Comment by kvolkovich-sc** [comment]
Looks like now it works ok. The issue was only on the first run.

`find ~/vcs -name "node_modules" | grep -v ".*node_modules.*node_modules.*"` .. `du -sh`shows ~ same results.

**Comment by zaldih** [comment]
**I think this problem is related to #40**
