### ISSUE TITLE
RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174

### ISSUE THREAD

**Issue by PierrickGT** [voidcosmos/npkill#29]
**Describe the bug**
I've used `npkill` for the first time today without any issue during the first couples try.
But now, every time I try to run it, I got this error: `RangeError [ERR_OUT_OF_RANGE]: The value of "err" is out of range. It must be a negative integer. Received 536870174`

**Screenshots**
<img width="1431" alt="Screenshot 2019-08-21 at 11 53 05" src="https://user-images.githubusercontent.com/2401738/63422237-4b169900-c40a-11e9-8d7f-f87f2e03b343.png">

 - OS: Mac OS 10.14.6
 - npkill version: 0.4.2

**Comment by zaldih** [comment]
Thank you for report this bug.
I have been investigating and it seems to be a node error ... Anyway, I suspect that it is related to the process of checking for updates.

I will investigate the solution to the problem. In the meantime, I will release a patch with a new parameter to avoid this check, which may allow you to launch npkill without problems.

**Comment by zaldih** [comment]
Version 0.4.3 is already on the air!
I have included a new parameter. I hope you can use npkill now.
`npkill --no-check-update <your-params>`

Let me know any news :D

**Comment by PierrickGT** [comment]
Thank you for the quick fix! It's working perfectly now.
