### ISSUE TITLE
npkill lists home directory

### ISSUE THREAD

**Issue by haykam821** [voidcosmos/npkill#40]
## Description

`npkill` lists the home directory as a ` node_modules` directory:

![npkill showing home directory](https://user-images.githubusercontent.com/24855774/63732799-e4e3a900-c843-11e9-83b9-73d37249df71.png)

## Reproduction

1. Run `npkill --sort size`.
2. Wait for search to complete.
3. Do other tasks, and return to the process.
4. `/Users/user/.` will appear on the list.

I was able to reproduce this multiple times.

## Expected Behavior

I expected for the home directory to not be listed.

## Additional Information

I am using macOS Mojave 10.14, with `npkill` version 0.5.0, `npm` version 6.10.2, and `node` version 12.8.1.

**Comment by zaldih** [comment]
Hi there! Thanks for reporting this bug and for the details.
Could you check if this same error happens in previous versions? Trying for example:
`npx npkill@0.4.0` or `npx npkill@0.3.0`

**Comment by LegalOwl** [comment]
Hi there,

so far I was unable to reproduce this issue on macOS Catalina 10.15.7 with the last version of npkill (0.7.2). Could you please verify if you can still reproduce this issue in the latest version and if you can produce it all the time or if it just occurs occasionally?

**Comment by PDavid** [comment]
Hi All,

I was able to reproduce this issue on Ubuntu 20.04 LTS with `npkill v0.7.2`.

![image](https://user-images.githubusercontent.com/1415396/96366819-61bd9a80-114a-11eb-9577-29c66c6e506a.png)

I tried this several times with the latest version and the issue occurs every time.

Also tried but cannot reproduce the issue with `0.3.0` or `0.4.0`,

**Comment by zaldih** [comment]
Parece I think we can say that all npkill problems related to miscalculated 'releasable space' are related to this problem rather than others, since the calculation of the 'releasable space' is added (maybe even several times) to the parent directory.

***
However, this behavior does **not become dangerous** since very early versions of the package added very advanced security layers to prevent precisely these directories from being deleted.

![npkill prevent delete](https://user-images.githubusercontent.com/16844185/113484463-b2cb0c00-94a8-11eb-86cd-2a2f8d33ee7c.gif)

https://github.com/voidcosmos/npkill/blob/5a9106f4717480a371a02854413bbfaa46ae18fd/src/services/files.service.ts#L32-L34

**Comment by zaldih** [comment]
### EUREKA!!!
**CHUNKS, chunks are the problem!**

In unix, files are searched using 'find'. This command is launched using the `child_process` node module, `spawn`.

I have found that **spawn** outputs the results in character chunks, and it seems obvious that this does not respect line breaks.

That is, if there are many, many results at once (which you would expect if you scan from the user directory, where the cache directories of many applications such as yarn are located), npkill will receive them in 2 or more parts, and this was not contemplated, so he will have truncated results, **and eventually match that truncation precisely with the start of the path.**

Using `--sort size` you can clearly observe this problem, but when it is not used, the phenomenon may be hidden among the thousands of results.

I have been able to test one of these truncations: 
![chunk-problem](https://user-images.githubusercontent.com/16844185/113485091-33d7d280-94ac-11eb-97de-6095688c8950.png)


https://github.com/voidcosmos/npkill/blob/5a9106f4717480a371a02854413bbfaa46ae18fd/src/services/unix-files.service.ts#L14-L20
