### ISSUE TITLE
Add Ethereum address to FUNDING.yml

### ISSUE THREAD

**Issue by lastmjs** [voidcosmos/npkill#41]
I'd like to see an Ethereum address added to the `custom` property of the `FUNDING.yml` file. This would allow a canonical address to send funds to. For example, I'm building a project that allows developers to setup one recurring donation that is split between all of their dependencies with an Ethereum address: https://sustainus.io

**Comment by zaldih** [comment]
Thanks for the recommendation. Added in e3fa9acb66f65be45b7da0b9d24a4200b057ab8b
