### ISSUE TITLE
Cannot destructure `name` of undefined or null on key press

### ISSUE THREAD

**Issue by yogain123** [voidcosmos/npkill#42]
<img width="990" alt="Screenshot 2019-08-29 at 12 48 11 PM" src="https://user-images.githubusercontent.com/14003377/63919083-a58fa500-ca5b-11e9-9adf-06749b29bbd5.png">

**Comment by zaldih** [comment]
Thanks for opening the issue!
This problem looks like #31 .

When does the error appear? when you press cursor down or another key?

I can say that it is a mac, right? By any chance you are using an external keyboard?

**Comment by yogain123** [comment]
Hu Zaldih,
The error appeared when I by mistake pressed option+z
The error is coming every time when press option+z
I am not using any external keyboard.
Yes Its mac.

**Comment by zaldih** [comment]
Thanks for the details!! I think I know where the error is and we will fix it

**Comment by zaldih** [comment]
Fixed on 39fbea4de9cd2c3414a298d02c99b32bb7325964 🎉 
It will be included in the next update.

**Comment by yogain123** [comment]
Okay . Thanks for letting me know
