### ISSUE TITLE
Text is misaligned

### ISSUE THREAD

**Issue by miguelmota** [voidcosmos/npkill#43]
<img width="507" alt="Screen Shot 2019-09-04 at 9 06 11 AM" src="https://user-images.githubusercontent.com/168240/64271996-487c6f00-cef3-11e9-896d-9b8853ecaa09.png">

**Comment by NyaGarcia** [comment]
Will fix it as soon as possible :)

**Comment by zaldih** [comment]
We have been aware of this for some time. I think we're going to remove the emoji library.

**Comment by zaldih** [comment]
#### Version 0.6.0 is already on the air! 🎉 
We have definitely made the decision to erase those "emojis", so there is nothing that overlaps.
