### ISSUE TITLE
excludeDirs.flat() is not a function

### ISSUE THREAD

**Issue by ladmerc** [voidcosmos/npkill#47]
**Is your feature request related to a problem? Please describe.**
Using the `exclude` option logs an error `excludeDirs.flat is not a function`. This is because the `.flat` method user [here](https://github.com/voidcosmos/npkill/pull/44/files#diff-03dc3fc6bad605160a87e47ee854b23dR67) [only exists from node 11.0.0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat). 

**Describe the solution you'd like**
I'm not sure if other similar newer methods are used elsewhere in the code, but it'd be nice to document the node versions required. Ideally though, it'll be nice to use alternative methods that exist in older versions, or a polyfill. This would make the library more portable

**Describe alternatives you've considered**
It works without `exclude`. In my local `node_modules/npkill`, I added [this](https://stackoverflow.com/a/50993569/4255034) polyfill from stackoverflow.

A more robust polyfill can be found [here](https://github.com/jonathantneal/array-flat-polyfill/blob/master/src/flat.js). 

**Additional context**

**Comment by zaldih** [comment]
Wow you are absolutely right. We launched very quickly to operate the exclude feature but forget to check compatibility precisely _(big mistake)_.

### Thank you very much for reporting the error!!
Of course, your PR will be more than welcome if you want to do it!

**Comment by ladmerc** [comment]
Got it. What would be preferred: updating the docs to specify the node version required, or adding a polyfill for the `.flat` method

**Comment by zaldih** [comment]
I think the most interesting thing would be to make npkill as compatible as possible for everyone. So a good polyfill would be the right thing to do.

If you need more information don't hesitate to ask

**Comment by zaldih** [comment]
Closing due to the fact that node11 will no longer be compatible soon
