### ISSUE TITLE
--help does not print the list of commands out of view

### ISSUE THREAD

**Issue by zaldih** [voidcosmos/npkill#50]
**Describe the bug**
--help does not print the list of commands out of view

**To Reproduce**
1. Open a terminal with a height less than 25 rows (v0.6.0)
2. Type `npkill -h`
3. You can see how the last rows do strange things, and omit the output of commands that do not fit in the terminal.

**Expected behavior**
It is expected to list all available commands as shown [here
](https://github.com/voidcosmos/npkill#options) regardless of terminal size.

**Screenshots**
![image](https://user-images.githubusercontent.com/16844185/67898650-feb1ad00-fb60-11e9-8dcd-541411f97175.png)
![image](https://user-images.githubusercontent.com/16844185/67898677-11c47d00-fb61-11e9-99c2-840dccceff1e.png)

 - OS: Tested in Arch. I imagine it applies to all systems.
 - Version: Probably since the --help command was implemented.

**Additional context**
May need to change the system by which the command list is printed :(

**Comment by tanmayrajani** [comment]
what do you think of using something like [commander.js](https://github.com/tj/commander.js)?

**Comment by NyaGarcia** [comment]
Hi @tanmayrajani ! First of all, sorry for the delay, life has been hectic :sweat_smile: 
Thank you for opening the issue and letting us know, we hadn't realised it did that. About commander.js, we'd prefer keeping npkill as lightweight as possible, so we'll initially try and fix this issue without using any external libraries. Thanks for the suggestion though :blush:

**Comment by zaldih** [comment]
Yay! thanks to @Nexxel  this bug has been fixed :tada:  (#62 )
