### ISSUE TITLE
npx npkill fails with "Cannot read property 'path' of undefined"

### ISSUE THREAD

**Issue by orestes** [voidcosmos/npkill#52]
**Describe the bug**

**To Reproduce**
1. Open a terminal
2. Run `npx npkill`
3. The bottom-left corner displays a message: "Cannot read property 'path' of undefined"

**Expected behavior**
npkill runs normally and displays a list of directories

**Screenshots**
![image](https://user-images.githubusercontent.com/618107/69361129-18d83a00-0c8c-11ea-8276-617f795377bd.png)

 - OS: MAC OS X 10.14.6
 - Version: npkill v0.6.0

**Comment by zaldih** [comment]
In this time the related methods have undergone many changes, so it should not be a problem today.
If it continues to be a problem, do not hesitate to reopen and add more details.

Thank!
