### ISSUE TITLE
[Feature request]: quick scroll

### ISSUE THREAD

**Issue by pawel2105** [voidcosmos/npkill#53]
**Describe the solution you'd like**
Would be awesome to be able to hold shift + cursor arrow to skip 10 or 20 line positions because scrolling through thousands of directories takes a long time.

**Describe alternatives you've considered**
Trying to exclude folders but that doesn't work as mentioned [here](https://github.com/voidcosmos/npkill/issues/19).

**Comment by zaldih** [comment]
Thank you for the issue and sorry for taking so long to reply.
Finally this will be solved very soon together with #100
