### ISSUE TITLE
MacOS 10.15.1 - The directory cannot be deleted. 

### ISSUE THREAD

**Issue by JoeEarly** [voidcosmos/npkill#59]
**Describe the bug**
On MacOS, I get the following error when attempting to delete files:

> The directory cannot be deleted. Do you have permission?

 Have tried with sudo and non-sudo accounts

**To Reproduce**
1. Run npkill with or without sudo command. 
2. Attempt to delete an item from the list displayed 
3. See error

**Expected behavior**
Item is deleted with no error 

**Screenshots**
<img width="1104" alt="Screenshot 2019-12-11 at 11 34 34" src="https://user-images.githubusercontent.com/5208459/70618243-386ade80-1c0a-11ea-890f-002bd6e01553.png">

 - OS:  MacOS 10.15.1
 - Version: 0.6.0

**Comment by zaldih** [comment]
Thank you very much for opening the issue and sorry for the delay.

I can't replicate the problem. In any case, the deletion method underwent a big change and should not be a problem today.

If it continues to be a problem, do not hesitate to reopen
