### ISSUE TITLE
Program hang when folder is deleted

### ISSUE THREAD

**Issue by soriac** [voidcosmos/npkill#61]
**Describe the bug**
When npkill finishes searching it displays 0mb releasable space, despite showing multiple node_modules folders. On folder deletion, the program hangs. After five minutes, I killed the process with task manager and found that it succeeded at deleting the folder, but got stuck anyways.

**To Reproduce**
1. Run cmder
2. Run npkill
3. Select a node_modules folder and hit space

**Expected behavior**
The program shouldn't hang. Also, it should be able to calculate folder size.

**Screenshots**
![image](https://user-images.githubusercontent.com/12989318/71528809-77628a80-28c0-11ea-95d7-66daff14ea8e.png)

 - OS: Windows 7
 - Version 0.6.0

**Additional context**
I suspect it may have something to do with file paths, you can see in the screenshots that the first part of the path uses one type of separator, and exactly after $PWD it switches separator type.

After a really long time (about half an hour) the program managed to unhang itself, after deleting a really small (< 1mb) node_modules folder. Also, after "unhanging", it calculated the size of two other really small node_modules folders. I was thinking maybe my hard drive was having some trouble, but Crystal Disk Info is reporting good HDD health.

**Comment by Mudassar045** [comment]
It's also happening on Ubuntu 18.0.4

**Comment by zaldih** [comment]
This bug should have been fixed with the versions released since then (thanks to the reporting of this problem and others, much of the windows deletion code was rewritten), so I'm going to close the issue.
If anyone has this same problem, please feel free to reopen :)
