### ISSUE TITLE
List Navigation - Page Up/Page Down [PgUp/PgDn/Home/End]

### ISSUE THREAD

**Issue by danieldjewell** [voidcosmos/npkill#66]
Hi!

Cool project -- was just giving it a shot, kinda amazing how some of the modules folders add up in size... 

Was doing what I usually do (I use console programs/interfaces _a lot_) ... and went to hit Page Up/Page Down to navigate ... and then also hit Home/End to navigate. To my surprise, nothing happened! 

I had a quick look in the code, looks like there _isn't_ a page up function really. I didn't look at the code in-depth yet to have enough information to recommend an implementation, but functionally, I think it might be nice to: 

* Bind ```[PgUp]``` and ```[PgDn]``` (the actual keys) to a page up/down
  * Alternatively (or additionally, maybe?) , if it's not possible to bind those keys, perhaps a capital letter ```[J]``` and ```[K]``` for page up/down... 
* Bind ```[Home]``` and ```[End]``` to jump to the top and end of the list
  * Alternatively/Additionally, consider maybe binding other commonly used keys to jump to top ... ```[j]``` / ```[k]``` are vi/vim/nvim-esque commands ...
  * Maybe ```[H]``` for "Jump to top of screen" and ```[L]``` for "Jump to bottom of screen" (but not "Top of entire list" and "Bottom of Entire list"...)
  * Maybe ```[g]``` (lowercase) for "Top of entire list" and ```[G]``` for "Bottom of entire list" (this would be vi/vim/nvim-esque - and also "less"-esque.) 
* *[This just came to mind, didn't yet search this...]* some key to change the sort order once the program is running as opposed to having to start it all over again (maybe [s]? to just cycle through different sorting methods?)

https://github.com/voidcosmos/npkill/blob/2d5e0e28a2cee8c202cec360005414f0cc706ca7/src/controller.ts#L59-L72

**Comment by zaldih** [comment]
**Hi!** Thanks for opening this issue and participating in the project. 
I do recall this functionality being on our // TODO list, but for some reason we never got around to implementing it (probably because of the ‘small’ amount of extra complexity that calculating the cursor’s new position entails.) We will take this into account though. Hopefully we can have it ready for the next version! 
I’ll let you know if we incorporate this into our code :)

**Comment by zaldih** [comment]
Hey!
I'm happy to announce that this issue is now complete 🎉 

Completing #100 ,  I just commit e93ded65a9cd038fca163849600671cff3fb243b to implement pgUp, pgDown, HOME and END.
