### ISSUE TITLE
Folder sizes always blank

### ISSUE THREAD

**Issue by arissberg** [voidcosmos/npkill#67]
**Describe the bug**
1. The folder, releasable space and space saved are always 0 or nothing.
2. The list of folders is blank after search, but appears when you cursor down.

**To Reproduce**
1. create a new zsh shell
2. change to projects directory
3. run `npx npkill`

**Expected behavior**
Expected to see folder sizes and list of folders after search completes

**Screenshots**
 - OS: MacOS 10.14.6
 - Version (ran with npx npkill)
<img width="1055" alt="Screen Shot 2020-03-16 at 12 23 34 PM" src="https://user-images.githubusercontent.com/1923932/76779332-8fd89780-6781-11ea-94fa-dfe58537bf75.png">

![npkill](https://user-images.githubusercontent.com/1923932/76783858-0331d780-6789-11ea-85e1-50075e251619.png)

**Comment by donavon** [comment]
me too!

**Comment by addyosmani** [comment]
I was running into this issue too but downgraded to https://github.com/voidcosmos/npkill/releases/tag/v0.6.0 which seems to work fine.

**Comment by marcins** [comment]
Possibly related to #70 - though weird that some people get no folder sizes, and some get no folders!

**Comment by zaldih** [comment]
It has definitely been a problem introduced in version 0.7.0 that seems to only affect mac for some mysterious reason.

@marcins  has found what seems to be the source of the problem https://github.com/voidcosmos/npkill/issues/70#issuecomment-608909316
