### ISSUE TITLE
Polyglot package system kill

### ISSUE THREAD

**Issue by sashvoncurtis** [voidcosmos/npkill#68]
When is gemkill, pubkill, headerkill, pykill coming? :)

**Comment by zaldih** [comment]
Hahaha!
We’re actually working on a little something that will allow npkill to take care of the dependencies for all those languages! 
Also, @tuqqu (hi!) has created [killposer](https://github.com/tuqqu/killposer) for the PhP ecosystem.

**Comment by sashvoncurtis** [comment]
Awesome ! 
Dependency management aint easy,  especially for multiple languages, looking forward to future releases!
