### ISSUE TITLE
Deleting actual code files and messing up git when using yarn workspaces.

### ISSUE THREAD

**Issue by saisandeepvaddi** [voidcosmos/npkill#81]
**Describe the bug**
First of all. Thanks for a cool library.

It turned out a little dangerous to use this when using workspaces.

If the project has yarn workspaces each with its own package.json in subdirectories, npkill is actually deleting package.json files in workspace folders and also some of the js files. If there is no git, I'd have lost all my work.

**To Reproduce**

I encountered this when my project has 
1. Yarn workspaces with two subdirectories each with its own package.json. Project is using Git of course.
2. Ran npx npkill.
3. Selected the node_modules and pressed SPACE key
4. It deleted node_modules along with package.json files in subdirectories which are workspaces.

I created a project to see if I can reproduce. And it happened again. Please find the repo at [https://github.com/saisandeepvaddi/npkill-test](https://github.com/saisandeepvaddi/npkill-test).

**Expected behavior**
It shouldn't delete any files outside node_modules folder.

**Screenshots**
![0pDI3ZZx9l](https://user-images.githubusercontent.com/13838175/90687891-917c1f00-e23b-11ea-90ce-9b2585c7db1f.gif)

 - OS: Windows
 - Version - Latest (I used npx)

**Comment by adi518** [comment]
I ran into this as well. It just deletes stuff it should never delete. Extremely dangerous bug. 👎

**Comment by NyaGarcia** [comment]
Wow, that should definitely NOT be happening. I'm really, really sorry if it deleted anything important.

We have a guard clause that checks whether or not the file is safe to delete, so I really have no idea with this is happening. Maybe it's related to this workspaces feature. I've never used it before and don't know how it works, but it might be what is causing the issue. I'll investigate and try my best to solve it. If you guys have any suggestions, I'd love to hear them.

Once again, I'm VERY sorry if Npkill deleted anything important.

**Comment by NyaGarcia** [comment]
Turns out that Yarn workspaces aliases workspace directories as /node_modules/workspace-name via symbolic link, which is what was causing the trouble. Should be fixed in #86. 

Here's the result of running Npkill with the latest changes on the https://github.com/saisandeepvaddi/npkill-test repo:

![npkill-yarn-fix](https://user-images.githubusercontent.com/37065748/99154250-9d4a7680-26ae-11eb-99ff-5adc13a52141.gif)

**Comment by adi518** [comment]
Getting an error now (on Windows):
```console
Callback must be a function. Received { recursive: true }
```

**Comment by NyaGarcia** [comment]
Are you by any chance using version 10 of Node.js? Updating to version 12+ should fix the error.

**Comment by adi518** [comment]
That could be, yes. I suggest throwing a friendly error if Node.js version is not supported.

**Comment by NyaGarcia** [comment]
We only just realized that Node.js versions previous to 12 aren't supported. Nice suggestion, we'll implement it asap. It'll serve as a patch until we can add support for previous Node.js versions.

**Comment by adi518** [comment]
So I checked and I'm getting this error with Node 12, on Windows 10.
