### ISSUE TITLE
Show Loading/Progress when delete a folder

### ISSUE THREAD

**Issue by angel-codes** [voidcosmos/npkill#82]
**Is your feature request related to a problem? Please describe.**

Once the list of folders is loaded, when pressing "Space" on an item, it seems that the CLI is stuck, seconds/minutes later (depending on the size of the folder) the "DELETE" flag appears at the beginning of the item.

**Describe the solution you'd like**
I don't know if this is already included, but it would be great to add some kind of "loading" or a "progress" while the folder is being deleted so that the user really knows that the operation is taking place.

**Describe alternatives you've considered**
No.

**Additional context**

I currently use this tool in:
- Windows 10 
- Fluent Terminal / Windows Terminal

**Comment by zaldih** [comment]
Thanks for opening the issue!  and I regret the delay in answering.

The program should not freeze while deleting the selected directory. In fact, as of 0.7.0 ([v0.7.0 changes](https://github.com/voidcosmos/npkill/releases/tag/v0.7.0)) the "loading" indicator was incorporated (you can see the gif) as you suggest, so **this is effectively a bug**. Good catch.

As soon as I can access a windows machine I will try to reproduce it and find the solution to this problem (unless someone finds it before :D)
