### ISSUE TITLE
Paths show trailing slash if directory is provided with trailing slash

### ISSUE THREAD

**Issue by wbobeirne** [voidcosmos/npkill#83]
**Describe the bug**

When you use the `-d` flag to provide a path, if you include a trailing slash, the display of paths will show two slashes. Here's an example where I ran `npm run start -- -d ~/`

![Screen Shot 2020-10-25 at 7 53 32 PM](https://user-images.githubusercontent.com/649992/97123865-c5703680-16fb-11eb-8a7f-e51f4c5619de.png)

**To Reproduce**
1. Run `npkill -d ~/`
2. Confirm output contains two slashes after the provided directory

**Expected behavior**

Strip the trailing slash

**Screenshots**

See above

 - OS: macOS
 - Version: master branch

**Comment by zaldih** [comment]
Very good observation. Thank you very much for opening the issue and providing the solution :hugs:
