### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by liuxin-0101** [voidcosmos/npkill#85]
Is it necessary to install and use him in the project?

**Comment by NyaGarcia** [comment]
No, you don't need to install Npkill globally to use it. 

All you need to do is run: `npx npkill` inside your project directory (or from anywhere you like, depending on the option that you're using). You can find more information on how to use Npkill in the official website:

https://npkill.js.org/

**Comment by liuxin-0101** [comment]
Thank you very much for your reply
