### ISSUE TITLE
Add Dark Mode Switch to https://npkill.js.org/

### ISSUE THREAD

**Issue by ExtremTechniker** [voidcosmos/npkill#92]
Please add a dark mode switch to your webpage [https://npkill.js.org](https://npkill.js.org/)

Thank you.

**Comment by ArthurKa** [comment]
Such a very convenient markdown link.

**Comment by ExtremTechniker** [comment]
Sorry. I forget to insert it as link, and not as `code`

**Comment by ArthurKa** [comment]
That's OK. No problem.

**Comment by zaldih** [comment]
Hey!
It is certainly a simple and interesting proposal. Definitely like it.
If someone is encouraged to implement it go ahead! And if not, I'll do it as soon as I can get some time :)

**Comment by ArthurKa** [comment]
@zaldih, so where is https://npkill.js.org repo?

**Comment by ExtremTechniker** [comment]
I think it is the `gh-pages` branch

**Comment by zaldih** [comment]
@ArthurKa yeah! In gh-pages branch :)
Let me know if you want me to assign you the issue :)

**Comment by ArthurKa** [comment]
Yeah, sure :)

**Comment by ArthurKa** [comment]
@zaldih, so when will it be reviewed?

**Comment by zaldih** [comment]
Welcome **DARK MODE!**
I don't know how the web didn't have that before. It looks awesome!
Thanks @ArthurKa  for the effort and @ExtremTechniker  for proposing it.

The change has been merged and published to the world.

**Comment by ArthurKa** [comment]
;)
